### ISSUE TITLE
401 Error when use Streaming API

### ISSUE THREAD

**Issue by dmnlk** [atig/atig#66]
Installed latest atig.rb in CentOS and ruby version is 2.3

```

$ ruby --version   
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

```

I got these error when connect Streaming API endpoint..

```

Exception `Atig::Stream::APIFailed' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1471 - 401 Authorization Required
E, [2016-02-22T10:19:08.293021 #3639] ERROR -- : [Atig::Scheduler] #<Atig::Stream::APIFailed: 401 Authorization Required>
        /home/user/atig/atig/lib/atig/stream.rb:40:in `block in watch'
        /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1446:in `block in transport_request'
        /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http/response.rb:163:in `reading_body'
        /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1445:in `transport_request'
        /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1407:in `request'
        /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
        /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:853:in `start'
        /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        /home/user/atig/atig/lib/atig/stream.rb:38:in `watch'
        /home/user/atig/atig/lib/atig/agent/user_stream.rb:21:in `block in initialize'
        /home/user/atig/atig/lib/atig/scheduler.rb:47:in `block in stream'
        /home/user/atig/atig/lib/atig/exception_util.rb:20:in `block (3 levels) in daemon'
        /home/user/atig/atig/lib/atig/exception_util.rb:7:in `safe'
        /home/user/atig/atig/lib/atig/exception_util.rb:20:in `block (2 levels) in daemon'
        /home/user/atig/atig/lib/atig/exception_util.rb:20:in `loop'
        /home/user/atig/atig/lib/atig/exception_util.rb:20:in `block in daemon'

D, [2016-02-22T10:19:08.293323 #3639] DEBUG -- : ["https://userstream.twitter.com/1.1/user.json"]
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/request_proxy/base.rb:79: warning: extra states are no longer copied: {"oauth_consumer_key"=>["####"], "oauth_token"=>["#####"], "oauth_signature_method"=>["HMAC-SHA1"], "oauth_timestamp"=>["1456103948"], "oauth_nonce"=>["####"], "oauth_version"=>["1.0"]}

```

but other REST API can connect.
any suggestion?

**Comment by dmnlk** [comment]
added `-d  `  option 

```

[~/atig/atig]$ ruby -d exe/atig -d                                                                                                                                                    [10:43:05]
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems.rb:1241 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems.rb:1250 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- did_you_mean
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- net/irc
Using Ext extension for JSON.
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- punycode
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:132 - cannot load such file -- punycode
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- jcode
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:132 - cannot load such file -- jcode
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- twitter-text
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text.rb:1: warning: assigned but unused variable - patch
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/regex.rb:25: warning: mismatched indentations at 'end' with 'def' at 11
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/regex.rb:54: warning: assigned but unused variable - patch
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/regex.rb: warning: character class has duplicated range
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/regex.rb: warning: character class has duplicated range
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/regex.rb: warning: character class has duplicated range
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/regex.rb: warning: character class has duplicated range
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/regex.rb: warning: character class has duplicated range
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/rewriter.rb:11: warning: shadowing outer local variable - last_index
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/extractor.rb:191: warning: assigned but unused variable - position
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/validation.rb:52: warning: assigned but unused variable - e
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/twitter-text-1.7.0/lib/twitter-text/hit_highlighter.rb:78: warning: shadowing outer local variable - index
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- jcode
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:132 - cannot load such file -- jcode
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- jcode
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:132 - cannot load such file -- jcode
Exception `NameError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/class_loader.rb:68 - uninitialized constant Object::BigDecimal
Exception `NameError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/core_ext.rb:17 - method `to_yaml' not defined in Object
Exception `NameError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/core_ext.rb:30 - method `yaml_as' not defined in Module
Exception `NameError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/deprecated.rb:82 - undefined method `to_yaml_properties' for class `Object'
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- oauth
/home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/client/helper.rb
        from exe/atig:13:in  `<main>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/atig/atig/lib/atig.rb:13:in  `<top (required)>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/atig/atig/lib/atig/gateway.rb:1:in  `<top (required)>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/atig/atig/lib/atig/gateway/session.rb:12:in  `<top (required)>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/atig/atig/lib/atig/oauth.rb:2:in  `<top (required)>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in  `rescue in require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth.rb:10:in  `<top (required)>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/client/helper.rb:2:in  `<top (required)>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:4:in  `<top (required)>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/client/net_http.rb:2:in  `<top (required)>'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/request_proxy/net_http.rb:69: warning: assigned but unused variable - auth_params
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:13: warning: File.exists? is a deprecated name, use File.exist? instead
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/consumer.rb:13: warning: File.exists? is a deprecated name, use File.exist? instead
/home/user/atig/atig/lib/atig/oauth-patch.rb:8: warning: method redefined; discarding old escape
/home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/oauth-0.4.7/lib/oauth/helper.rb:11: warning: previous definition of escape was here
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- sqlite3
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- sqlite3/2.3/sqlite3_native
Exception `LoadError' at /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:132 - cannot load such file -- sqlite3/2.3/sqlite3_native
/home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/x86_64-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
I, [2016-02-22T10:44:21.681028 #8109]  INFO -- : Host: localhost Port:16668

```
