### ISSUE TITLE
Test "ruby2.3" failed: Failure/Error: db.execute "VACUUM status"

### ISSUE THREAD

**Issue by uwabami** [atig/atig#67]
Debian の BTS より
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841574

Relevant part (hopefully):
>      Failure/Error: db.execute "VACUUM status"
> 
>      SQLite3::SQLException:
>        unknown database status
>      # ./lib/atig/db/statuses.rb:126:in `block in cleanup'
>      # ./lib/atig/db/sql.rb:27:in `execute'
>      # ./lib/atig/db/statuses.rb:121:in `cleanup'
>      # ./spec/db/statuses_spec.rb:180:in `block (2 levels) in <top (required)>'
> 

とりあえずご報告までに。

**Comment by uwabami** [comment]
#73 関連で修正済み
